apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - grafanadashboard.yaml

configMapGenerator:
  - name: grafana-dashboard-connectivity-probe
    files:
      - dashboard.json=connectivity-probe-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
